### ISSUE TITLE
Shell quoting does not quote \r

### ISSUE THREAD

**Issue by miikka** [leahneukirchen/lr#1]
I'd expect that shell quoting would quote characters like `\r` in file names. Here's what happens:

```
% touch $'foo\r'
% lr
.
'foo
```

(By the way: I played around with lr a bit and it looks quite handy!)

**Comment by leahneukirchen** [comment]
Actually this works as intented, you just don't see it because the terminal emulator overwrites the line:

```
% lr | xxd
00000000: 2e2f 0a27 666f 6f0d 270a                 ./.'foo.'.
% lr | while read f; do eval stat $f; done
  File: ‘.’
...
  File: ‘foo\r’
...
```

It would be nicer perhaps to output `$'string'` quoting, but this is not POSIX sh yet...
