### ISSUE TITLE
lr fails to build on hurd-i386

### ISSUE THREAD

**Issue by nicoonoclaste** [leahneukirchen/lr#15]
@ucko [reported](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=880852) that lr fails to build on hurd, due to `PATH_MAX` not being defined.

The suggested fix is to use `pathconf(3)` to look up `_PC_PATH_MAX`, at least on platforms that lack a `PATH_MAX`.

**Comment by nicoonoclaste** [comment]
@ucko Can you check whether https://github.com/chneukirchen/lr/commit/d2b437219f20ef51a1964ccec0241770626c3510 builds on Hurd?

**Comment by ucko** [comment]
Yes, albeit with some warnings that probably aren't a big deal:

```
lr.c:1087:2: warning: #warning fstype lookup not implemented on this platform, keeping st_dev as number [-Wcpp]
 #warning fstype lookup not implemented on this platform, keeping st_dev as number
  ^~~~~~~
lr.c: In function 'color_size_on':
lr.c:1450:13: warning: comparison is always true due to limited range of data type [-Wtype-limits]
  else if (s <  2*1048*1024*1024LL) c = 208;
             ^
lr.c:1451:13: warning: comparison is always true due to limited range of data type [-Wtype-limits]
  else if (s < 50*1024*1024*1024LL) c = 202;
             ^
```

Thanks for the quick fix!

**Comment by leahneukirchen** [comment]
I'm willing to accept a patch that implements fstype for hurd.
