### ISSUE TITLE
Printing only files in breadth-first search

### ISSUE THREAD

**Issue by occivink** [leahneukirchen/lr#18]
Hi,

I would like to print files (not directories) in breadth-first order.  I tried `lr -B -t 'type != d'` but it does not print anything, even though `lr -D -t 'type != d'` works as expected.

Is this a limitation in the breadth-first search?

**Comment by leahneukirchen** [comment]
Well, `type != d` will ignore the toplevel dir and thus nothing happens. I'll look into how to improve this.

In the meantime, you can use `lr -B | lr -t 'type != d' -`.

**Comment by occivink** [comment]
How come this doesn't happen on depth-first search?

**Comment by leahneukirchen** [comment]
Depth-first always traverses and filters in hindsight.

**Comment by occivink** [comment]
I see. Maybe in addition to `skip`, `prune` and `print` a "traverse-but-do-not-print" expression could solve this?

**Comment by leahneukirchen** [comment]
Please try https://github.com/leahneukirchen/lr/tree/color-hidden

**Comment by occivink** [comment]
Thank you, that seems to work well. For what it's worth this is what I wanted to achieve:
`lr -B -t 'type == d ? ((name ~~ "build*" || name == ".git") ? prune && skip : skip) : print`

**Comment by leahneukirchen** [comment]
Merged.
