### ISSUE TITLE
lr printing uninitialized data (edge case)

### ISSUE THREAD

**Issue by notwa** [leahneukirchen/lr#22]
`recurse` is meant to initialize `st` through `stat` or `lstat`, but [the error handling here is suspect.](https://github.com/leahneukirchen/lr/blob/01ceb9c89ddeffbb45f14b68a26b45734f7cf5b2/lr.c#L2270) for instance, invoking `lr -1l` may fail to stat a file, with `lstat` yielding -1 and `errno=EACCES`. then, the block I linked falls through to the rest of the function body, despite `st` still being uninitialized.

I'm not sure how one would trigger this behavior on Linux or BSD (fooling around with `mount` perhaps?), but it's quite simple on Windows with cosmopolitan libc (yes, I apologize for the esoteric platform):
```
$ lr.com -1l /c/Windows/System32 | grep /config/
drws-ws-wx 123145302440352 0 0 17594333530624 2022-06-10 19:52 C:/Windows/System32/config/
```
the numbers for inode count and filesize are both pointers leftover from the stack. don't worry about the `0 0`, that's normal.

adding an `else return 0;` after the `errno != EACCES` branch mitigates the issue, but also omits the file from the listing. is there a better solution?

also, you might want to look over the operator precedence here. I suppose it doesn't matter, since both `stat` and `lstat` only ought to ever return `0` or `-1`, right? so being truthy is adequate to detect failure. _I think._ just wondering if that's intentional.

**Comment by leahneukirchen** [comment]
I don't see a better way that to initialize the stat buffer here, does that yield reasonable output then?
