### ISSUE TITLE
Go Beyond One Level of Directories

### ISSUE THREAD

**Issue by jgarte** [leahneukirchen/lr#26]
>        -1      Don't go below one level of directories.

Hi, is it supported to go beyond one level of directories?

I didn't see a flag for it 🦆

**Comment by leahneukirchen** [comment]
That's the default behavior.

**Comment by jgarte** [comment]
@leahneukirchen I realize my original question was not clear enough.

How do I go to 2, 3 or 7 levels only and specifically?

**Comment by leahneukirchen** [comment]
lr -t 'depth >= 7 ? prune : print'

**Comment by jgarte** [comment]
How do I run it for `8` or `6` levels though? JK JK JK 😹 

Awesome, Thanks @leahneukirchen! 

TIL: `-t`
