### ISSUE TITLE
Doc: find/regex example doesn't work

### ISSUE THREAD

**Issue by winks** [leahneukirchen/lr#5]
On Debian Wheezy my "find -regex" doesn't work as in the README

```
$  find . -regex 'c$' # nope
$  find . -regex '.*.c' # yes
./lr.c
$  find . -regex '.*.c$' # yes
./lr.c
$  find . -regex ".*.c" # double quotes work
./lr.c

$  lr -t 'path =~ c$' # missing quotes, xfail
lr: parse error: invalid string at 'c$'
$  lr -t 'path =~ "c$"' # works
lr.c
$  lr -t "path =~ 'c$'" # why do double quotes not work
lr: parse error: invalid string at ''c$''

```

**Comment by leahneukirchen** [comment]
The README only states `lr -t 'path =~ "c$"'` which works?

Strings only work for `"` currently... perhaps I'll add other syntaxes later. (I think barewords would be nice too...)

**Comment by winks** [comment]
> Doc: find/regex example doesn't work

the _find_ example doesn't work. I need `.*.c$` instead of `c$`
Agree on " not working => close :)

**Comment by leahneukirchen** [comment]
Fixed.
